apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: canarydeployment
  namespace: istio-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  selector:
    matchLabels:
      app: nginx   # Label selector matching the labels of the pods managed by the deployment
  service:
    port: 80
  analysis:
    interval: 1m
    threshold: 10
    maxWeight: 50
    stepWeight: 10
