apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-deployment-controller
  namespace: k8s-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment-controller
  namespace: k8s-deployment
spec:
  selector:
    matchLabels:
      app: k8s-deployment-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-deployment-controller
    spec:
      containers:
        - name: controller
          image: registry.k8s.io/k8s-deployment/controller:v1.8.1@sha256:e5c4824e7375fcf2a393e1c03c293b69759af37a9ca6abdb91b13d78a93da8bd
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
            - containerPort: 8443
              name: webhook
          resources:
            requests:
              cpu: 100m
              memory: 90Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-deployment-admission-create
  namespace: k8s-deployment
spec:
  template:
    spec:
      containers:
        - name: create
          image: registry.k8s.io/k8s-deployment/kube-webhook-certgen:v20230407@sha256:543c40fd093964bc9ab509d3e791f9989963021f1e9e4c9c7b6700b02bfb227b
          args:
            - create
            - --host=k8s-deployment-controller-admission,k8s-deployment-controller-admission.$(POD_NAMESPACE).svc
            - --namespace=$(POD_NAMESPACE)
            - --secret-name=k8s-deployment-admission
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
