kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-deployment-full-access-role
  namespace: k8s-deployment
rules:
  - apiGroups: ["","extensions", "apps", "storage.k8s.io"]
    resources: ["*"]
    verbs:     ["*"]

---

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-deployment-full-access-role-binding
  namespace: k8s-deployment
subjects:
  - kind: ServiceAccount
    name: k8s-deployment
    namespace: k8s-deployment
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: k8s-deployment-full-access-role

---

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-deployment-integration-access-role
  namespace: k8s-deployment
rules:
  - apiGroups: ["","extensions", "apps"]
    resources: ["*"]
    verbs:     ["create","get","describe","delete","list","watch", "patch", "update"]
  - apiGroups: ["networking.istio.io"]
    resources: ["gateways", "virtualservices"]
    verbs:     ["create","get","describe","delete","list","watch"]

---

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-deployment-integration-access-role-binding
  namespace: k8s-deployment
subjects:
  - kind: ServiceAccount
    name: k8s-deployment
    namespace: k8s-deployment
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: k8s-deployment-integration-access-role

---

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-deployment
  namespace: k8s-deployment

