apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: nginx-canary
  namespace: istio-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx   # Name of the Deployment to watch
  selector:
    matchLabels:
      app: nginx   # Label selector matching the labels of the pods managed by the Deployment
  service:
    port: 80
  analysis:
    interval: 1m
    threshold: 10
    maxWeight: 50
    stepWeight: 10
